name: em

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib=3.5.2
  - git
  - simpeg
  - pyvista
  - cmake
  - mkl-devel
  - pkg-config
  - dill
  - jupyter
  - jupyterlab
  - ipympl
  - ipywidgets
  - mkl-devel
  - pkg-config
